spring.application.name=tempmail


spring.datasource.url=jdbc:postgresql://localhost:5432/tempmail
spring.datasource.username=vidhan
spring.datasource.password=vidhan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#mailgun.webhook.signing-key=${MAILGUN_SIGNING_KEY}
mailgun.webhook.signing-key=dummy-key-for-local-testing