spring.application.name=tempmail


spring.datasource.url=jdbc:postgresql://localhost:5432/tempmail
spring.datasource.username=vidhan
spring.datasource.password=vidhan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#mailgun.webhook.signing-key=key-f7c11bade20c6566a52562e3430ad321
mailgun.webhook.signing-key=dummy-key-for-local-testing