spring.application.name=tempmail
spring.config.import=optional:file:./application-local.properties


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tempmail}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tempmail}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:change-me-local-only}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


mailgun.webhook.signing-key=${MAILGUN_WEBHOOK_KEY}
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.api-key=${MAILGUN_API_KEY}
